# frozen_string_literal: true

<<BLOCKINGIO
Generated by Gemini

APPLICATION (User Space)                KERNEL (System Space)
              |                                       |
              |               syscall                 |
      [1] Call read() ------------------------------> | [2] Check for data,
              |               |                       |     No data ready
              |               |                       |        |
              |               |                       |        v
              |           (BLOCKED)                   |        |
              |           (SLEEPING)                  |        |
              |               |                       | [3] Data arrives on
              |               |                       |     network
              |               |                       |        |
              |               |                       |        |
              |               v                       |        v
              | <------------------------------------ | [4] Copy data from
      [5] read() returns                              |     Kernel buffer to
              |                                       |     User buffer
      [6] Process Data                                |
              |                                       |
BLOCKINGIO

# This example shows a server that processes client sockets with the basic
# read(2) call (wrapped by IO#read I guess). The entire program is blocked
# until the read() call returns. Please note that I am reallyjust messing
# around here to get a feel for using TCP sockets and Socket programming in
# general.
module BlockingIO
  require 'socket'

  # Server handles client connections serially in a single thread
  class Server
    def initialize
      @listening_socket = Socket.new(:INET, :STREAM)
      @local_addr = Socket.pack_sockaddr_in(2211, '0.0.0.0')
      @listening_socket.setsockopt(:SOL_SOCKET, :SO_REUSEADDR, true)
      @listening_socket.bind @local_addr
      @listening_socket.listen(10)
      @client_no = 0
    end

    def start
      loop do
        # accept() blocks while waiting for clients to connect
        # Here we process 1 client at a time
        client, client_addr = @listening_socket.accept
        @client_no += 1
        puts "Client #{@client_no} connected"
        process client
        client.close
        puts "#{@client_no} successfully closed"
      end
    end

    def process(client)
      # read 10 bytes each time
      # socket receives EOF when it closes its endpoint
      until (request = client.read(100)).nil?
        puts "#{@client_no}: #{request}"
      end
    end
  end

  # Sends the server simple messages
  class Client
    ADJECTIVES = %w[cool lame bespoke indubitable rhetorical wise intelligent].freeze

    attr_reader :client

    def initialize
      @client = Socket.new(:INET, :STREAM)
      @remote_addr = Socket.pack_sockaddr_in(2211, 'localhost')
      @connection_retry_limit = 5
      @id = self.hash.to_s(16)[0..6]
    end

    def send_messages_and_close
      @client.connect @remote_addr
      3.times { @client.write("You are #{ADJECTIVES.sample}") }
    rescue => e
      puts "CLIENT EXCEPTION: #{e.message}"
      @connection_retry_limit -= 1
      sleep 0.3
      retry if @connection_retry_limit.positive?
      puts "Client #{@id} failed to connect"
    ensure
      @client.close
    end
  end

  def self.run_clients
    clients = 20.times.map do
      Thread.new { BlockingIO::Client.new.send_messages_and_close }
    end
  ensure
    clients.each &:join
  end
end

if ARGV.last == 'server'
  puts 'Server program'
  BlockingIO::Server.new.start
elsif ARGV.last == 'client'
  puts 'Client program'
  BlockingIO.run_clients
end
