# frozen_string_literal: true

# rubocop:disable Lint/MissingCopEnableDirective
# rubocop:disable Lint/RedundantCopDisableDirective
# rubocop:disable Lint/UselessAssignment
# rubocop:disable Metrics/MethodLength
# rubocop:disable Metrics/ClassLength
# rubocop:disable Naming/MethodParameterName
# rubocop:disable Naming/AccessorMethodName
# rubocop:disable Style/EmptyMethod

<<NONBLOCKINGIO
Generated by Gemini

APPLICATION (User Space)                KERNEL (System Space)

              |                                       |
      [1] Call read() (Non-Blocking) ---------------> |
              |                                       | [2] Check for data
              | <------------------------------------ |     No Data Yet
      [3] Returns EWOULDBLOCK                         |
              |                                       |
      [4] (Do other work or Loop)                     |
              |                                       |
      [5] Call read() (Non-Blocking) ---------------> |
              |                                       | [6] Check for data
              | <------------------------------------ |     No Data Yet
      [7] Returns EWOULDBLOCK                         |
              |                                       |
      [8] (Wait/Loop)                                 | [9] Data arrives from
              |                                       |     network interface
              |                                       |
      [10] Call read() (Non-Blocking) --------------> |
              |                                       | [11] Data exists!
              |                                       |         |
              | <------------------------------------ | [12] Copy data to
      [13] read() returns DATA                        |      User buffer
              |                                       |
NONBLOCKINGIO

# I am not going to implement this kind of server. It doesn't really seem like
# I would ever want to implement any kind of server this way. Perhaps in the
# future I will encounter a problem for which this busy polling business might
# actually be a good fit — in which case I will hopefully remember this io
# model.
