# frozen_string_literal: true


<<IOMULTIPLEXING
Generated by Gemini

APPLICATION (User Space)                KERNEL (System Space)
              |                                       |
      [1] Add FDs to Set {fd1, fd2...}                |
              |                                       |
      [2] Call select(Set) -------------------------> |
              |               |                       | [3] Monitor all FDs
              |           (WAITING)                   |     in the set.
              |    (Thread is "Blocked" here)         |        |
              |     waiting for ANY event             |     Sleep...
              |               |                       |        |
              |               |                       | [4] Data arrives on
              |               |                       |     fd2 and fd5
              |               |                       |        |
              | <------------------------------------ | [5] Mark fd2, fd5
      [6] select() returns                            |     as "Ready"
              |                                       |
      [7] Iterate through Set:                        |
          - fd1: Not ready                            |
          - fd2: READY -> call read() --------------> | [8] Copy data (fd2)
          - ...                                       | <------------------
IOMULTIPLEXING

# Non-Blocking IO Notes:
# 
# It seems that there is a lot going on with TCP server architecture and the
# resource I am using (Working With TCP Sockets by Jesse Storimer) covers a lot
# of ground in order to implement a "proper" client/server model using the
# TCP/Socket primitives that Ruby gives us out of the box. So below will just
# contain notes on the nonblocking versions of the various IO related methods
# in Ruby.
#
# IO.select:
#   - Invokes select(2), which monitors multiple fds, waiting until one or more
#   of the fds becomes ready for the specified IO operation
#   - blocks the process until it receives an interrupt from the OS notifying
#   the blocked process that the given fds are ready
#   - signature: ([read_sockets], [write_sockets], [exceptional_sockets], timeout) -> [[], [], []]
#   - timeout arg sets a time limit on how long this method blocks for, to
#   prevent this method from blocking indefinitely
#   - EOF: for read-sockets, remember that sockets can return nil or an
#   EOFError depending on how they were initialized
#   - ACCEPT: need specific logic for reading the listening socket that accepts
#   connections
#   - CONNECT: On the client side, monitor the writable server socket with
#   select(2) after rescuing Errno::EINPROGRESS. There is actually a good deal
#   of stuff that we have to do handle here with care. See connect_nonblock
#   below
#
# IO#read_nonblock:
#   - accepts int -- num bytes to read, but may return less than this many
#   bytes
#   - similar to readpartial -- reads up to maxlen bytes from the read byte
#   buffer:
#     - Ruby will first invoke read(2) and actually possibly reads more bytes
#     than the specified maxlen into its internal buffers -- so when we invoke
#     this call again, Ruby can just read from its internal buffers and not
#     call read(2) a second time.
#   - This method returns instantly -- if no bytes read, raises
#   IO::EAGAINWaitReadable
#   - can just rescue IO::WaitReadable to handle this
#   - Can throw any error that read(2) would throw. See the man page.
#
# IO#write_nonblock:
#   - this method can perform a partial write, as opposed to the regular write
#   - The normal write method will write all the data, but may invoke write(2)
#   syscall several times in order to write everything
#   - The write(2) call can block in 2 situations:
#     1. Receiving end of th TCP connection has not yet acknowledged receipt of
#     the pending data, and our write-end has sent as much data as is allowed.
#     If the network is too congested, TCP ensures that the network is never
#     flooded with packets -- the OS will hold off sending more data under
#     these conditions.
#     2. TCP Flow Control: the OS network stack has determined that the
#     receiving host is not able to handle any more data, so it holds off on
#     sending more for the time being, until it receives a confirmation that
#     the receiving host is able to accept more packets.
#
# IO#accept_nonblock:
#   - returns immediately
#   - If the listen queue is empty, this raises Errno::EAGAIN rather than
#   blocking like the normal accept method.
#   - see man page for errors.
#   - This method is used by the listening socket. Like connect_nonblock below,
#   there is some nuance with the use of this method especially when used in
#   conjunction with IO.select
#
# IO#connect_nonblock:
#   - tries to connect to the remote endpoint, returns 0 on success
#   - See man pages for all errors that may throw
#   - may immediately raise Errno::EINPROGRESS if the connection is not able to
#   complete immediately.
#   - should rescue IO::WaitWritable (which extends above error), like the
#   write_nonblock method, which indicates to us that the request is in
#   progress
#   - Proper way to handle this is in conjunction with IO.select
#
# NOTE: All of the above non-blocking variants essentially just call the base
# syscalls with the O_NONBLOCK flag set, and so the most authoritative docs
# are -- in addition to the ruby docs -- the man pages (section 2).
# Moreover, it is clear from all of these docs that these nonblocking methods
# are intended to be used together with IO.select, which gives us the basic
# (and only) IO multiplexing primitive that comes with ruby. In particular,
# most linux systems come with epoll(7), and I believe macOS/FreeBSD come with
# kqueue. These offer more efficient alternatives to both poll(2) and select(2)
# syscalls, which both execute in linear time, proportional to the number of
# fds being monitored for io-readiness.
#
# There really seems to be only one library that provides better io-primitives
# than the builtin ones: nio4r
# With regards to this chess project, I think that first I will just implement
# the server with the builtins, then if I'm feeling spicy I will play around
# with nio4r. Looking at the docs, it seems quite comparable to the regular
# select(2) way of doing things, except that it gives us a stateful wrapper as
# opposed to the stateless IO.select.
